"""agent_checkpoints"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = 'b0fd9ff7e8d7'
down_revision = '730a_search_indexes'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_checkpoints',
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('checkpoint_ns', sa.String(length=200), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('checkpoint', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('checkpoint_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pending_writes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_checkpoints')
    # ### end Alembic commands ###
